### ISSUE TITLE
Change FindWindow(0, "Geometry Dash") to FindWindow(0, L"Geometry Dash") in Flirt.cpp

### ISSUE THREAD

**Issue by Lightium** [absoIute/Flirt#1]
Title.

**Comment by absoIute** [comment]
That would cause issues (similar to that) with anyone using single-byte character set in their config.

Instead I've used FindWindowA explicitly in [this](https://github.com/absoIute/Flirt/commit/442678baa46567c186d775fa53637b105f18266f) commit to fix your issue.
